/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface WcSplit {
    'debug': boolean;
    'direction': string;
    'items': { name: string, size: number }[] | string;
  }
}

declare global {


  interface HTMLWcSplitElement extends Components.WcSplit, HTMLStencilElement {}
  var HTMLWcSplitElement: {
    prototype: HTMLWcSplitElement;
    new (): HTMLWcSplitElement;
  };
  interface HTMLElementTagNameMap {
    'wc-split': HTMLWcSplitElement;
  }
}

declare namespace LocalJSX {
  interface WcSplit extends JSXBase.HTMLAttributes<HTMLWcSplitElement> {
    'debug'?: boolean;
    'direction'?: string;
    'items'?: { name: string, size: number }[] | string;
    'onResized'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'wc-split': WcSplit;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


